-- MySQL Script generated by MySQL Workbench
-- Fri Jul 22 19:23:50 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`status` ;

CREATE TABLE IF NOT EXISTS `mydb`.`status` (
  `idstatus` INT NOT NULL,
  `descr` VARCHAR(45) NULL,
  PRIMARY KEY (`idstatus`),
  UNIQUE INDEX `idstatus_UNIQUE` (`idstatus` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`licence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`licence` ;

CREATE TABLE IF NOT EXISTS `mydb`.`licence` (
  `idlicence` INT NOT NULL,
  `descr` VARCHAR(45) NULL,
  PRIMARY KEY (`idlicence`),
  UNIQUE INDEX `idlicence_UNIQUE` (`idlicence` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`call`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`call` ;

CREATE TABLE IF NOT EXISTS `mydb`.`call` (
  `idcall` VARCHAR(6) NOT NULL,
  `last` VARCHAR(45) NOT NULL,
  `first` VARCHAR(45) NOT NULL,
  `suffix` VARCHAR(45) NULL,
  `status` INT NOT NULL,
  `license` INT NULL,
  PRIMARY KEY (`idcall`),
  UNIQUE INDEX `idcall_UNIQUE` (`idcall` ASC),
  INDEX `idstatus_idx` (`status` ASC),
  INDEX `idlicense_idx` (`license` ASC),
  CONSTRAINT `idstatus`
    FOREIGN KEY (`status`)
    REFERENCES `mydb`.`status` (`idstatus`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idlicense`
    FOREIGN KEY (`license`)
    REFERENCES `mydb`.`licence` (`idlicence`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`state`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`state` ;

CREATE TABLE IF NOT EXISTS `mydb`.`state` (
  `idstate` INT NOT NULL,
  `descr` VARCHAR(2) NULL,
  PRIMARY KEY (`idstate`),
  UNIQUE INDEX `idstate_UNIQUE` (`idstate` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`home`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`home` ;

CREATE TABLE IF NOT EXISTS `mydb`.`home` (
  `idcall` VARCHAR(6) NOT NULL,
  `addr1` VARCHAR(45) NULL,
  `addr2` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `state` INT NULL DEFAULT 'VA',
  `zip` INT NULL,
  `phone` INT NULL,
  `pphone` TINYINT(1) NULL,
  `cell` INT NULL,
  `pcell` TINYINT(1) NULL,
  `email` VARCHAR(45) NULL,
  `pemail` TINYINT(1) NULL,
  PRIMARY KEY (`idcall`),
  UNIQUE INDEX `idcall_UNIQUE` (`idcall` ASC),
  INDEX `idstate_idx` (`state` ASC),
  CONSTRAINT `idcall`
    FOREIGN KEY (`idcall`)
    REFERENCES `mydb`.`call` (`idcall`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idstate`
    FOREIGN KEY (`state`)
    REFERENCES `mydb`.`state` (`idstate`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`work`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`work` ;

CREATE TABLE IF NOT EXISTS `mydb`.`work` (
  `idcall` VARCHAR(6) NOT NULL,
  `addr1` VARCHAR(45) NULL,
  `addr2` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `state` INT NULL,
  `zip` INT NULL,
  `phone` INT NULL,
  `pphone` INT NULL,
  `cell` INT NULL,
  `pcell` INT NULL,
  `email` VARCHAR(45) NULL,
  `pemail` INT NULL,
  PRIMARY KEY (`idcall`),
  UNIQUE INDEX `idcall_UNIQUE` (`idcall` ASC),
  INDEX `idstate_idx` (`state` ASC),
  CONSTRAINT `idcall0`
    FOREIGN KEY (`idcall`)
    REFERENCES `mydb`.`call` (`idcall`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idstate`
    FOREIGN KEY (`state`)
    REFERENCES `mydb`.`state` (`idstate`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`certificates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`certificates` ;

CREATE TABLE IF NOT EXISTS `mydb`.`certificates` (
  `idcertificates` INT NOT NULL,
  `descr` VARCHAR(45) NULL,
  PRIMARY KEY (`idcertificates`),
  UNIQUE INDEX `idcertificates_UNIQUE` (`idcertificates` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`havecerts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`havecerts` ;

CREATE TABLE IF NOT EXISTS `mydb`.`havecerts` (
  `idcall` VARCHAR(6) NOT NULL,
  `type` INT NOT NULL,
  PRIMARY KEY (`idcall`),
  UNIQUE INDEX `idcall_UNIQUE` (`idcall` ASC),
  INDEX `idcertificates_idx` (`type` ASC),
  CONSTRAINT `idcall`
    FOREIGN KEY (`idcall`)
    REFERENCES `mydb`.`call` (`idcall`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idcertificates`
    FOREIGN KEY (`type`)
    REFERENCES `mydb`.`certificates` (`idcertificates`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`radiotype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`radiotype` ;

CREATE TABLE IF NOT EXISTS `mydb`.`radiotype` (
  `idradiotype` INT NOT NULL,
  `descr` VARCHAR(45) NULL,
  PRIMARY KEY (`idradiotype`),
  UNIQUE INDEX `idradiotype_UNIQUE` (`idradiotype` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`haveradios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`haveradios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`haveradios` (
  `idcall` VARCHAR(6) NOT NULL,
  `type` INT NOT NULL,
  PRIMARY KEY (`idcall`),
  UNIQUE INDEX `idcall_UNIQUE` (`idcall` ASC),
  INDEX `idradiotype_idx` (`type` ASC),
  CONSTRAINT `idcall`
    FOREIGN KEY (`idcall`)
    REFERENCES `mydb`.`call` (`idcall`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idradiotype`
    FOREIGN KEY (`type`)
    REFERENCES `mydb`.`radiotype` (`idradiotype`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`yn`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`yn` ;

CREATE TABLE IF NOT EXISTS `mydb`.`yn` (
  `idyn` INT NOT NULL,
  `descr` CHAR(1) NULL,
  PRIMARY KEY (`idyn`),
  UNIQUE INDEX `idyn_UNIQUE` (`idyn` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`supplemental`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`supplemental` ;

CREATE TABLE IF NOT EXISTS `mydb`.`supplemental` (
  `idsupplemental` INT NOT NULL,
  `descr` VARCHAR(45) NULL,
  PRIMARY KEY (`idsupplemental`),
  UNIQUE INDEX `idsupplemental_UNIQUE` (`idsupplemental` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`havesupplement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`havesupplement` ;

CREATE TABLE IF NOT EXISTS `mydb`.`havesupplement` (
  `idcall` VARCHAR(6) NOT NULL,
  `type` INT NULL,
  PRIMARY KEY (`idcall`),
  UNIQUE INDEX `idcall_UNIQUE` (`idcall` ASC),
  INDEX `type_idx` (`type` ASC),
  CONSTRAINT `idcall`
    FOREIGN KEY (`idcall`)
    REFERENCES `mydb`.`call` (`idcall`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idsupplemental`
    FOREIGN KEY (`type`)
    REFERENCES `mydb`.`supplemental` (`idsupplemental`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`issues`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`issues` ;

CREATE TABLE IF NOT EXISTS `mydb`.`issues` (
  `idissues` INT NOT NULL,
  `descr` VARCHAR(45) NULL,
  PRIMARY KEY (`idissues`),
  UNIQUE INDEX `idissues_UNIQUE` (`idissues` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`haveissues`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`haveissues` ;

CREATE TABLE IF NOT EXISTS `mydb`.`haveissues` (
  `idcall` VARCHAR(6) NOT NULL,
  `type` INT NULL,
  PRIMARY KEY (`idcall`),
  UNIQUE INDEX `idcall_UNIQUE` (`idcall` ASC),
  INDEX `type_idx` (`type` ASC),
  CONSTRAINT `idcall`
    FOREIGN KEY (`idcall`)
    REFERENCES `mydb`.`call` (`idcall`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `type`
    FOREIGN KEY (`type`)
    REFERENCES `mydb`.`issues` (`idissues`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`status`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`status` (`idstatus`, `descr`) VALUES (1, 'Active');
INSERT INTO `mydb`.`status` (`idstatus`, `descr`) VALUES (2, 'Inactive');
INSERT INTO `mydb`.`status` (`idstatus`, `descr`) VALUES (3, 'SK');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`licence`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`licence` (`idlicence`, `descr`) VALUES (1, 'Novice');
INSERT INTO `mydb`.`licence` (`idlicence`, `descr`) VALUES (2, 'Technician');
INSERT INTO `mydb`.`licence` (`idlicence`, `descr`) VALUES (3, 'Tech +');
INSERT INTO `mydb`.`licence` (`idlicence`, `descr`) VALUES (4, 'General');
INSERT INTO `mydb`.`licence` (`idlicence`, `descr`) VALUES (5, 'Advanced');
INSERT INTO `mydb`.`licence` (`idlicence`, `descr`) VALUES (6, 'Extra');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`certificates`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`certificates` (`idcertificates`, `descr`) VALUES (1, 'IS-700 NIMS');
INSERT INTO `mydb`.`certificates` (`idcertificates`, `descr`) VALUES (2, 'IS-800 NRF');
INSERT INTO `mydb`.`certificates` (`idcertificates`, `descr`) VALUES (3, 'IS-100 Intro ICS');
INSERT INTO `mydb`.`certificates` (`idcertificates`, `descr`) VALUES (4, 'IS-200 Basic ICS');
INSERT INTO `mydb`.`certificates` (`idcertificates`, `descr`) VALUES (5, 'ICS-300 Intermediate ICS');
INSERT INTO `mydb`.`certificates` (`idcertificates`, `descr`) VALUES (6, 'ICS-400 Advanced ICS');
INSERT INTO `mydb`.`certificates` (`idcertificates`, `descr`) VALUES (7, 'Red Cross Intro to Disasters');
INSERT INTO `mydb`.`certificates` (`idcertificates`, `descr`) VALUES (8, 'Adult CPR');
INSERT INTO `mydb`.`certificates` (`idcertificates`, `descr`) VALUES (9, 'Adult CPR with AED');
INSERT INTO `mydb`.`certificates` (`idcertificates`, `descr`) VALUES (10, 'Infant/Child CPR');
INSERT INTO `mydb`.`certificates` (`idcertificates`, `descr`) VALUES (11, 'First Aid');
INSERT INTO `mydb`.`certificates` (`idcertificates`, `descr`) VALUES (12, 'Red Cross Shelter Management');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`radiotype`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`radiotype` (`idradiotype`, `descr`) VALUES (1, 'VHF HT');
INSERT INTO `mydb`.`radiotype` (`idradiotype`, `descr`) VALUES (2, 'VHF/UHF HT');
INSERT INTO `mydb`.`radiotype` (`idradiotype`, `descr`) VALUES (3, 'Other HT');
INSERT INTO `mydb`.`radiotype` (`idradiotype`, `descr`) VALUES (4, 'HF Mobile');
INSERT INTO `mydb`.`radiotype` (`idradiotype`, `descr`) VALUES (5, 'VHF Mobile');
INSERT INTO `mydb`.`radiotype` (`idradiotype`, `descr`) VALUES (6, 'VHF/UHF Mobile');
INSERT INTO `mydb`.`radiotype` (`idradiotype`, `descr`) VALUES (7, 'All mode Mobile');
INSERT INTO `mydb`.`radiotype` (`idradiotype`, `descr`) VALUES (8, 'HF Base');
INSERT INTO `mydb`.`radiotype` (`idradiotype`, `descr`) VALUES (9, 'All mode Base');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`yn`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`yn` (`idyn`, `descr`) VALUES (0, 'N');
INSERT INTO `mydb`.`yn` (`idyn`, `descr`) VALUES (1, 'Y');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`supplemental`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`supplemental` (`idsupplemental`, `descr`) VALUES (1, 'TNC');
INSERT INTO `mydb`.`supplemental` (`idsupplemental`, `descr`) VALUES (2, 'APRS');
INSERT INTO `mydb`.`supplemental` (`idsupplemental`, `descr`) VALUES (3, 'Portable Antenna');
INSERT INTO `mydb`.`supplemental` (`idsupplemental`, `descr`) VALUES (4, 'Signalink');
INSERT INTO `mydb`.`supplemental` (`idsupplemental`, `descr`) VALUES (5, '4-WD vehicle');
INSERT INTO `mydb`.`supplemental` (`idsupplemental`, `descr`) VALUES (6, 'Portable Shelter');
INSERT INTO `mydb`.`supplemental` (`idsupplemental`, `descr`) VALUES (7, 'Generator');
INSERT INTO `mydb`.`supplemental` (`idsupplemental`, `descr`) VALUES (8, 'Laptop');
INSERT INTO `mydb`.`supplemental` (`idsupplemental`, `descr`) VALUES (9, 'Portable Printer');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`issues`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`issues` (`idissues`, `descr`) VALUES (1, 'Do not have radio');
INSERT INTO `mydb`.`issues` (`idissues`, `descr`) VALUES (2, 'One HT battery');
INSERT INTO `mydb`.`issues` (`idissues`, `descr`) VALUES (3, 'No transportation');
INSERT INTO `mydb`.`issues` (`idissues`, `descr`) VALUES (4, 'Home-based operator');
INSERT INTO `mydb`.`issues` (`idissues`, `descr`) VALUES (5, 'Cannot walk long distances');
INSERT INTO `mydb`.`issues` (`idissues`, `descr`) VALUES (6, 'Wheelchair required');
INSERT INTO `mydb`.`issues` (`idissues`, `descr`) VALUES (7, 'Visual imparement');
INSERT INTO `mydb`.`issues` (`idissues`, `descr`) VALUES (8, 'Hearing imparement');
INSERT INTO `mydb`.`issues` (`idissues`, `descr`) VALUES (9, 'Willing to work near animals');

COMMIT;

